### ISSUE TITLE
Please remove data.table::key2

### ISSUE THREAD

**Issue by mattdowle** [hope-data-science/akc#1]
Hello,

Please could you remove this line : 
https://github.com/hope-data-science/akc/blob/36778e037a9e1f030dd748164e538c107f6eec23/NAMESPACE#L77

The next release of data.table contains note 2:
![image](https://user-images.githubusercontent.com/2779998/72026643-006ab180-3231-11ea-8cb5-cc7a36d8e938.png)

I don't think you use `key2`. You just import it. So removing the import should be all that's required. Otherwise the next `data.table` release will cause `akc` to fail with error because `key2` is no longer exported.

Thanks, Matt

**Comment by hope-data-science** [comment]
Thank you for noting, I'll remove them right away.

If you have any way to deal with duplicated names from different packages, let me know.

Best, Hope
