### ISSUE TITLE
Error with Rake Created keywords

### ISSUE THREAD

**Issue by snvv** [hope-data-science/akc#5]
Hello 
I have a df with some text and I used skowraker to create keywords for each row.
When I run the script
> mydata %>% 
  keyword_clean(id = "doc_id",
                keyword = "keyword_rake",
                sep = ";",
                rmParentheses = TRUE,
                rmNumber = TRUE,
                lemmatize = FALSE,
                lemmatize_dict = NULL) -> clean_data

clean_data

> clean_data %>% 
  keyword_merge(  id = "doc_id",
                  keyword = "keyword_rake",
                  reduce_form = "lemma",
                  lemmatize_dict = NULL,
                  stem_lang = "porter") -> merged_data

I get the following error:

> Error in setnames(., old = c(id, keyword), new = c("id", "keyword")) : 
  Items of 'old' not found in column names: [keyword_rake]. Consider skip_absent=TRUE.

What is wrong in this case?
Regards

**Comment by hope-data-science** [comment]
Can you put your data and code in a repo so I can reproduce your results?

**Comment by snvv** [comment]
I apologize for the bug report. 
The bug was in my code.
It works as expected.
Regards
